doc.type.html
script
filename=covid strings4 key words.js
let original string=”
let word to add-
let updated string {original string} {word to add}
console log updated string
xovid strings4 key word list=[arcturus variant arc covid universe,work from home not only song,negative or positive,one of them not giving up,a lot of madness, 2020 ncaa tournament,news professional level,social distancing 3 ft,covid canceling conference
cdc clarified 3ft,inequity,healthcare inequities,one four-four,bubble ]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
covid strings4 reference list=[a:new covid-19 strain:what to know about arcturus (medicalnewstoday.com),b:the truth about the arc of the moral universe |huff post opinion archive,c:40 songs about working from home (pop,rap & more) -foundations of music,d:why was the coronavirus hard to predict? optimism didnt help. -the atlantic,e:scientists make major breakthrough that could stop covid forever(msn.com),f:the hustle (song) -wikipedia,g:ncaa cancels march madness tournaments,all other winter and spring championships(nbcnews.com),h:https://www.espn.com/mens-college-basketball/story/_/id/28893285/ncaa-tournaments-canceled-coronavirus,i:empty stadiums during pandemic provide less advantage for home teams,study finds - 
j:upi.com,three feet or six? k:distancing guideline for schools stirs debate -the new york times (nytimes.com),l:coronavirus conference gets canceled because of coronavirus |time,m:updated cdc guidance says3 feet of physical distancing is safe in schools|cnn,n:the covid variant in schools:what to know -the new york times (nytimes.com)
o:health disparities and equity in the era of covid-19 -pmc (nih.gov),p:the new covid booster is here:but will those at greatest risk get it?|benefits pro,q:espn films latest documentary “144” takes viewers inside the wnbas unprecedented 2020 season may 13 on espn - espn press room us.,r:sports bubbles are good places to study covid-19 -the verge, s:the second-generation covid]
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
A =Pc.CreateScript(A);
A.Attributes.Add(Foobar,{Type: Entity});
A.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
B=Pc.CreateScript(B);
B.Attributes.Add(Foobar,{Type: Entity});
B.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
C=Pc.CreateScript(C);
C.Attributes.Add(Foobar,{Type: Entity});
C.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
D=Pc.CreateScript(D);
D.Attributes.Add(Foobar,{Type: Entity});
D.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
E=Pc.CreateScript(E);
E.Attributes.Add(Foobar,{Type: Entity});
E.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
F=Pc.CreateScript(F);
F.Attributes.Add(Foobar,{Type: Entity});
F.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
G =Pc.CreateScript(G);
G.Attributes.Add(Foobar,{Type: Entity});
G.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
H=Pc.CreateScript(H);
H.Attributes.Add(Foobar,{Type: Entity});
H.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
I=Pc.CreateScript(I);
I.Attributes.Add(Foobar,{Type: Entity});
I.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
J =Pc.CreateScript(J);
J.Attributes.Add(Foobar,{Type: Entity});
J.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
K=Pc.CreateScript(K);
K.Attributes.Add(Foobar,{Type: Entity});
K.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
L=Pc.CreateScript(L);
L.Attributes.Add(Foobar,{Type: Entity});
L.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
M=Pc.CreateScript(M);
M.Attributes.Add(Foobar,{Type: Entity});
M.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
N=Pc.CreateScript(N);
N.Attributes.Add(Foobar,{Type: Entity});
N.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
O=Pc.CreateScript(O);
O.Attributes.Add(Foobar,{Type: Entity});
O.Prototype.Initialize = Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
template asset resource 
entity template instaniate
entity script foobar =this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instaniate
entity script foobar=this entity
entity reparnet (this.entity)
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instaniate
entity script foobar =this entity
entity reparnet (this.entity)
r=pc.create script(r);
r.ttributes.add(foobar,{type:entity});
r.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instaniate
entity script foobar =this entity
entity reparnet (this.entity)
s=pc.create script(s);
s.attributes.add(foobar,{type:entity});
s.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instaniate
entity script foobar =this entity
entity reparnet (this.entity)
t=pc.create script(t);
t.attributes.add(foobar,{type:entity});
t.prototype.initialize =function() 
console.log(this.foobar.name);
return filename
