doc.type html
script
html
head
filename=covid strings4 championship game .js
championship game=(highest and lowest remaining seeds ) 
team high seed= highest remaining seed 
team low seed = lowest remaining seed
rounddiv=covid strings4 championship round
matchupclassName = matchup;
matchupdiv.innerHTML =[team low seed versus team high seed]
roundDiv.AppendChild(MatchupDiv);
bracket.AppendChild(RoundDiv);
advancingTeam = slice(current teams)
java Util.Scanner
java.Util
questions[]questions={
question28
question29
question30
question31
question32
question33
question34
collections.shuffle(arrays.aslist(questions)
class myclass
constructor (non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
const myclass=newmyclass(concatenated) 
return category
if category==math problem:
prompt
log
else:
select from multiple choice
import syntax 
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
declare winner
if team high seed score>sixty=:
console.log(team high seed wins covid strings4)
else:
console.log(team low seed wins covid strings4)
return filename
