doc.type.html
html lang en
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings4’
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=keywords
heading2=online references
heading3=script templates
filename=covidstrings4keywords.js
let original string=”
let word to add-
let updated string {original string} {word to add}
console log updated string
<header.html>
keywords
key search words for covid strings4
covid strings4 key word list=[arcturus variant arc covid universe,work from home not only song,negative or positive,one of them not giving up,a lot of madness, 2020 ncaa tournament,news professional level,social distancing 3 ft,covid canceling conference
cdc clarified 3ft,inequity,healthcare inequities,one four-four,bubble ]
string manager non-concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
string manager concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
<header.html>
online references 
links to articles that correspond to phrases in covid strings4
covid strings4 reference list=[a:new covid-19 strain:what to know about arcturus (medicalnewstoday.com),b:the truth about the arc of the moral universe |huff post opinion archive,c:40 songs about working from home (pop,rap & more) -foundations of music,d:why was the coronavirus hard to predict? optimism didnt help. -the atlantic,e:scientists make major breakthrough that could stop covid forever(msn.com),f:the hustle (song) -wikipedia,g:ncaa cancels march madness tournaments,all other winter and spring championships(nbcnews.com),h:https://www.espn.com/mens-college-basketball/story/_/id/28893285/ncaa-tournaments-canceled-coronavirus,i:empty stadiums during pandemic provide less advantage for home teams,study finds - 
j:upi.com,three feet or six? k:distancing guideline for schools stirs debate -the new york times (nytimes.com),l:coronavirus conference gets canceled because of coronavirus |time,m:updated cdc guidance says3 feet of physical distancing is safe in schools|cnn,n:the covid variant in schools:what to know -the new york times (nytimes.com)
o:health disparities and equity in the era of covid-19 -pmc (nih.gov),p:the new covid booster is here:but will those at greatest risk get it?|benefits pro,q:espn films latest documentary “144” takes viewers inside the wnbas unprecedented 2020 season may 13 on espn - espn press room us.,r:sports bubbles are good places to study covid-19 -the verge, s:the second-generation covid vaccines are coming -scientific american,t:rihanna -umbrella lyrics | azlyrics.com]
<header.html>
script templates
code for accessing the references
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantite
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{Type: Entity});
f.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet(this.entity)
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
j=pc.create script(j);
j.attributes.add(foobar,{type:entity});
j.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.create script(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
l=pc.create script(l);
l.attributes.add(foobar,{type:entity});
l.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
r=pc.create script(r);
r.ttributes.add(foobar,{type:entity});
r.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
s=pc.create script(s);
s.attributes.add(foobar,{type:entity});
s.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
t=pc.create script(t);
t.attributes.add(foobar,{type:entity});
t.prototype.initialize =function() 
console.log(this.foobar.name);
return filename
